using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ResumeAI.Export.API.Interfaces;
using ResumeAI.Shared.DTOs;

namespace ResumeAI.Export.API.Services;

public class QuestPdfRenderer : IPdfRenderer
{
    public byte[] GeneratePdf(ExportData data)
    {
        var resume = data.Resume;
        var user = data.User;
        var sections = data.Sections;

        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Black).FontFamily(Fonts.Verdana));

                // HEADER: User Name and Contact Info
                page.Header().Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(titleCol =>
                        {
                            titleCol.Item().Text(user.FullName).FontSize(28).Bold().FontColor(Colors.Blue.Medium);
                            titleCol.Item().Text(resume.TargetJobTitle).FontSize(16).FontColor(Colors.Grey.Medium);
                        });

                        row.ConstantItem(150).AlignRight().Column(contactCol =>
                        {
                            contactCol.Item().Text(user.Email).FontSize(10).AlignRight();
                            if (!string.IsNullOrEmpty(user.Phone))
                                contactCol.Item().Text(user.Phone).FontSize(10).AlignRight();
                        });
                    });
                    
                    col.Item().PaddingTop(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                // CONTENT: Sections
                page.Content().PaddingVertical(10).Column(col =>
                {
                    foreach (var section in sections.Where(s => s.IsVisible).OrderBy(s => s.DisplayOrder))
                    {
                        col.Item().PaddingTop(15).Column(sectionCol =>
                        {
                            sectionCol.Item().Text(section.Title).FontSize(14).Bold().FontColor(Colors.Blue.Medium);
                            sectionCol.Item().PaddingTop(2).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                            sectionCol.Item().PaddingTop(5).Text(section.Content).LineHeight(1.2f);
                        });
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by ");
                    x.Span("ResumeAI Platform").Bold().FontColor(Colors.Blue.Medium);
                    x.Span(" — Page ");
                    x.CurrentPageNumber();
                });
            });
        }).GeneratePdf();
    }
}
